### ISSUE TITLE
AiCwebpage.htm is truncated when transmitted via send vs. sendall

### ISSUE THREAD

**Issue by robnee** [RinusW/WiPy#3]
In my environment at least it seems that conn.send doesn't send the entire page (AiCwebpage.htm) to the browser client but conn.sendall does.  Only about 1000 bytes are sent when using send.  I'm not sure if there is a reason to use one over the other though.

This is on the ESP8266.

**Comment by RinusW** [comment]
Probably this is due to the fact that your HTML page is larger (contains more bytes) than what fits in a single Http message. The use of sendall() solves this, and is preferable here over send().

**Comment by robnee** [comment]
Yes it is. Thank you for the explanation and for this simple code to get me started. Cheers.

Rob

On Dec 8, 2016, at 07:17, RinusW <notifications@github.com<mailto:notifications@github.com>> wrote:


Probably this is due to the fact that your HTML page is larger (contains more bytes) than what fits in a single Http message. The use of sendall() solves this, and is preferable here over send().

-
